[project]
name = "readgpt"
version = "0.1.0"
description = "ReadGPT - Summarize and chat with any article using AI"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "uvicorn>=0.34.0",
]
