services:
  - type: web
    name: readgpt-backend
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    buildFilter:
      paths:
        - /*.py
      ignoredPaths:
        - /*.test.py
  - type: web
    name: readgpt-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install; npm run build
    staticPublishPath: out
    pullRequestPreviewsEnabled: false
    buildFilter:
      paths:
        - frontend/**/*.js
      ignoredPaths:
        - frontend/**/*.test.js
